[project]
name = "hdf5_io"
version = "0.1.0"
description = "Import and export of general Python objects to HDF5 (TeNPy format)"
readme = {file = "README.rst", content-type = "text/x-rst"}
license-files = ["LICENSE"]
requires-python = ">=3.10"
license = "Apache-2.0"
keywords = ["hdf5", "h5py", "serialization"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Programming Language :: C++",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy",
    "h5py",
]

[project.optional-dependencies]
test = ["pytest>=6.0"]
lint = ["ruff", "flake8", "flake8-rst-docstrings", "sphinx-lint"]

[project.urls]
"Homepage" = "https://github.com/tenpy/hdf5_io"
"Source" = "https://github.com/tenpy/hdf5_io"

[build-system]
requires = ["scikit-build-core", "pybind11", "numpy>=2.0"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
cmake.version = ">=3.15"
build-dir = "build"
cmake.build-type = "Debug"
wheel.packages = ["hdf5_io"]

[tool.scikit-build.cmake.define]
BUILD_TESTING = {env = "BUILD_TESTING", default = "ON"}

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "error",
]

[tool.ruff]
line-length = 120
target-version = "py310"
exclude = ["scripts/", "src/python2/", "src/python3/"]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "UP",
    "ISC",
    "LOG",
    "INP",
    "D",
]
ignore = [
    "F403",
    "F405",
    "E741",
    "F541",
    "UP015",
    "UP008",
    "D102",
    "D105",
    "D107",
    "D203",
    "D213",
    "D400",
    "D401",
    "D415",
    "D417",
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
    "I",
    "E402",
]
"tests/*.py" = [
    "E501",
    "F841",
    "INP001",
    "D",
]

[tool.ruff.format]
quote-style = "single"
docstring-code-format = true
